spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: 'ci,test'
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:shareit'
    username: test
    password: test
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        transaction:
          interceptor: TRACE
