spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: eldar
    url: jdbc:h2:mem:shareit
    password: '702658'
  H2:
    console:
      enabled: true
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  config:
    activate:
      on-profile: 'ci,test'
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        transaction:
          interceptor: TRACE
