spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: eldar
    url: jdbc:postgresql://localhost:5432/postgres
    password: '702658'
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop

